[Variables]
SidebarContextTitle=#tEditWidgets#
SidebarContextAction=[!WriteKeyValue Variables SettingsTab "Widgets" "#@#Variables\Layout.inc"][!ToggleConfig "#ROOTCONFIG#" "Settings.ini"][!ActivateConfig "#ROOTCONFIG#" "Settings.ini"]
SidebarContextTitle2=#tDisableSidebar#
SidebarContextAction2=[!ShowFadeGroup "Rich"][!DeactivateConfig "#CURRENTCONFIG#"]
SidebarContextTitle3=#tQuitRainmeter#
SidebarContextAction3=[!Quit]
SidebarContextTitle4=